/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    projects: Project;
    employmentHistory: EmploymentHistory;
    educationHistory: EducationHistory;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    employmentHistory: EmploymentHistorySelect<false> | EmploymentHistorySelect<true>;
    educationHistory: EducationHistorySelect<false> | EducationHistorySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  /**
   * Generated from the project title unless edited manually.
   */
  slug: string;
  /**
   * Preserves legacy /featured/:projectId URLs during the Payload migration.
   */
  legacyProjectId?: string | null;
  featured?: boolean | null;
  /**
   * Lower numbers appear first on the public site.
   */
  sortOrder: number;
  summary: string;
  responsibilities?:
    | {
        title: string;
        copy?: string | null;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        language: string;
        id?: string | null;
      }[]
    | null;
  frameworks?:
    | {
        framework: string;
        id?: string | null;
      }[]
    | null;
  cmsPlatforms?:
    | {
        platform: string;
        id?: string | null;
      }[]
    | null;
  externalUrl?: string | null;
  screenshots?:
    | {
        /**
         * Public Firebase Storage download URL or preserved legacy media URL.
         */
        url: string;
        /**
         * Firebase Storage object path, when known.
         */
        storagePath?: string | null;
        orientation: 'landscape' | 'portrait';
        alt: string;
        caption?: string | null;
        order: number;
        fileName?: string | null;
        contentType?: string | null;
        /**
         * File size in bytes.
         */
        size?: number | null;
        width?: number | null;
        height?: number | null;
        id?: string | null;
      }[]
    | null;
  video?: {
    /**
     * Public Firebase Storage download URL or preserved legacy media URL.
     */
    url?: string | null;
    /**
     * Firebase Storage object path, when known.
     */
    storagePath?: string | null;
    posterUrl?: string | null;
    caption?: string | null;
    fileName?: string | null;
    contentType?: string | null;
    /**
     * File size in bytes.
     */
    size?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employmentHistory".
 */
export interface EmploymentHistory {
  id: string;
  company: string;
  role: string;
  summary: string;
  startDate: string;
  endDate?: string | null;
  /**
   * Optional human-readable duration, preserved from legacy content when needed.
   */
  durationLabel?: string | null;
  /**
   * Lower numbers appear first on the public site.
   */
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educationHistory".
 */
export interface EducationHistory {
  id: string;
  institution: string;
  location?: string | null;
  field: string;
  type: 'education' | 'continuingEducation' | 'certification';
  completionDate?: string | null;
  /**
   * Optional display value for non-date completions like "In Progress".
   */
  completionLabel?: string | null;
  /**
   * Lower numbers appear first on the public site.
   */
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'admins';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'employmentHistory';
        value: string | EmploymentHistory;
      } | null)
    | ({
        relationTo: 'educationHistory';
        value: string | EducationHistory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: string | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'admins';
    value: string | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  legacyProjectId?: T;
  featured?: T;
  sortOrder?: T;
  summary?: T;
  responsibilities?:
    | T
    | {
        title?: T;
        copy?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        language?: T;
        id?: T;
      };
  frameworks?:
    | T
    | {
        framework?: T;
        id?: T;
      };
  cmsPlatforms?:
    | T
    | {
        platform?: T;
        id?: T;
      };
  externalUrl?: T;
  screenshots?:
    | T
    | {
        url?: T;
        storagePath?: T;
        orientation?: T;
        alt?: T;
        caption?: T;
        order?: T;
        fileName?: T;
        contentType?: T;
        size?: T;
        width?: T;
        height?: T;
        id?: T;
      };
  video?:
    | T
    | {
        url?: T;
        storagePath?: T;
        posterUrl?: T;
        caption?: T;
        fileName?: T;
        contentType?: T;
        size?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employmentHistory_select".
 */
export interface EmploymentHistorySelect<T extends boolean = true> {
  company?: T;
  role?: T;
  summary?: T;
  startDate?: T;
  endDate?: T;
  durationLabel?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educationHistory_select".
 */
export interface EducationHistorySelect<T extends boolean = true> {
  institution?: T;
  location?: T;
  field?: T;
  type?: T;
  completionDate?: T;
  completionLabel?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: string;
  name: string;
  role: string;
  specialty?: string | null;
  headlines?:
    | {
        copy: string;
        id?: string | null;
      }[]
    | null;
  aboutCopy?:
    | {
        copy: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  services?:
    | {
        title: string;
        summary?: string | null;
        id?: string | null;
      }[]
    | null;
  contactInfo: {
    email: string;
    location?: string | null;
  };
  socialLinks?:
    | {
        platform: string;
        userName?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  tools?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  cmsPlatforms?:
    | {
        platform: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  specialty?: T;
  headlines?:
    | T
    | {
        copy?: T;
        id?: T;
      };
  aboutCopy?:
    | T
    | {
        copy?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  services?:
    | T
    | {
        title?: T;
        summary?: T;
        id?: T;
      };
  contactInfo?:
    | T
    | {
        email?: T;
        location?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        userName?: T;
        url?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        name?: T;
        id?: T;
      };
  tools?:
    | T
    | {
        name?: T;
        id?: T;
      };
  cmsPlatforms?:
    | T
    | {
        platform?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}